apiVersion: v1
kind: Secret
metadata:
    name: fishing-app-secret
    namespace: fishing
    labels:
        app.kubernetes.io/name: fishing-app
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fWK5wn7somr4JTV0DRQ24PjotJEhc3Gk2cwuxNcivw5XFEy7stqQRvt5pRiucz/JYdj9Ly8xzyUXnlX+UlDOCzdw,iv:WPdSbjCU/8xzEjxojXWUtNw/9ilWJ+caKgjmHOZIwrs=,tag:ReugxfDbZ7FqRX0hkB6jww==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:bAc6o6fRrxRlz5Vqtqj8LxLb0UM90sjjoanqepgoaClLf6XG8dZ+2KeJWG0l9EjmpM0Qiy4a7SBn0EBlCPv2G8PocayzQPCATn8kb1G33FBG/y0GZ/cUwBxRnWxVXqu0Jb/QKMUOOeOSU0CqPxsx+9OySDNAxx5clHqoQKRliiqYakkxl2QYgQ==,iv:6emsLNLIivAmqAgWSnHDx1KWGWETO7jVhZ0doUF02iQ=,tag:whnPcGZs45KmJQky7K2d5A==,type:str]
    #ENC[AES256_GCM,data:wJsowNmb8ITYmthhuWQFLz1oC4vSNok3QC6hxJo4RuY3rMz/L4UJAao4770yTM50M4iPE0Nz3h8=,iv:ny/1ce1fqK0Uflf7afYdBAOx3MWZjZQCX2Zx+PvTyUg=,tag:KX11826pxuXHhLzeOmvz9Q==,type:comment]
    DATABASE_URL_DIRECT: ENC[AES256_GCM,data:Dle2pTo+k7z/qqjYcFGdr/Ej+tvAy9hz08vUvdA36W8A1o9RicFg3vadtpl6iIXlWCvxaExnsvPP64k+v3iORZOSHVplSWbo2i6z28bwXXw9yQqPSnqzbbtaYHfgIl3bAsBtZLZbYMRx10FU8SsNRi6/I9aNrvuvGO9hKah75tXfQjtEAMz1yBHdMsQkIAG+,iv:rfFAk4GmAF217fgeirqSSR5X5toClazAcy4cORUSGuo=,tag:yTqq6e+sTs1kbNfHhbunDA==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:EOzNUcUDKB2X+J8W/696Na8xzEJ+i0Tl/Vwu7zlFkwZRm6BQ300VhRXKyYo=,iv:ppQWEOGHAsaLqpfHPeD2f6ygt5lXIEyB9+hGpGX9F30=,tag:8UYFwrotMxscXgvPujucgg==,type:str]
    AUTH_GOOGLE_ID: ENC[AES256_GCM,data:HJWA/Aaia5iJUhle/YMcXfGTWfhfKc+LFBR1MPshFzjGN7J8Fib98ndu9TRLsJPMBbKBb8zD6k58CRll8lsEShfIs+duQDg0,iv:mGL6mjkNM9zJDjFIljtMjtbjvMBfTyetlkHT9cirZrk=,tag:Lsp+frQgo5s5G8fmBjm/vg==,type:str]
    AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:HIHCg4B2/yYBeZGjee5uk1p7NDgDtzxzxvOSqnjUk3szv/E=,iv:LOwrXC/iubBxdIMjEeYFYVMGMYC0Epqg7Aem+I8WH6k=,tag:kHbdx0tQRJbRGl6UD5wnLA==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:bLa6qJKAlp+m5ie5YRpX8B//rXbQEhRQXrEujRSeac0=,iv:z6zBCmg+1d7FLysCSrn7prcY5oz1Ry2B93cXuwGFx1w=,tag:wO/Aa0kHwe3oputTDbKUVQ==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:PkedD3eZ2fNL6YjRb83ykBx3vmCZRmlQBuxeSvw71UQubbp7FiE8,iv:FXWmySa2phL5V8F4fa0S/eV+D6St4J5bvCtFHxauCrc=,tag:9jWuG7OF2kXlGYxFwmR93w==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:uGMM0JCRuyo4zYmdqssQSrFjOJ6gZr3OCgdCuns6uQs1oO7b,iv:68pWpdobmq31Bs53qUyouiQ3z8Epa8doegAoHryulb0=,tag:GHPZvsgjAy74ieWsboYrgA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:S9eeuGYZEImHmc4G5xnMwE+ohyG0zw==,iv:7F+3d4Se5QxAwz8O9H6g/GaHUR+TH0dxH/NDi+hZw2A=,tag:mw4lmg85Kr7xA9scyfhhaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT25qc0ZOQ3hmd0hOdXNE
            R081R2V3VUNmSkhiMjBrWURjaWM3eEduakdjCmxPOE9uOC84YTBBMXNjaWRhSlFM
            eVdlTDVUTzNCSmJGK1l1aTBIL0o3MEEKLS0tIExOSkNZS0xveldzQWJ0Q0k5M1N2
            WkVFajlHYTJHRFE1ZWJKdjM1MzlzZDAKEGT5LGXUA+p4CNCqNPztazzvfZFRecSr
            u6du4c4zmhqTDQY5fCYmhbSRDyRX37bsB/emrsQpmzhSDg4z6DCrMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwpnls59pm7a542w3s4le2sgrcqpvtxtchxumdl4qhwph4xu25wqpqjxpn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL3FCcEJpN1JNSjFxNjBW
            VGdCLzhqM2cvNFBhc0wxbk1DaDR5akdUaFVFCmhuRFBpeXVjTWhCUElFeFF0bXli
            bklYdVk3cCsrUURiNURLeFVXcno3QXcKLS0tIE8rZHEwdnVXMVlNd0MxNjRpSlBB
            L0hYU0tFY28wNHR4anhmN1VSR0RmZWMKPdGj07BgWdo6oLy493lSBissGlIJzL75
            Vkn6bgGjt3379S7ve+R3iq9HO6jQN1UOE0snhfbgCshxyFJVuVt1zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19243y8pewm9rq8ldjffptyvkfex2ytem2wncdhzj4gl8q0awyqqq0l56wk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVFdrVTJDRkdFU2Z4SlF0
            NXhjcEJnUEtFWjdVR28xQVlBUEx5VktmSmw0ClRyd2hzcExkdnFMMjhvdktCa1BR
            djlMTVlreW5uam8xaityc0pkYmoyNFkKLS0tIDBSVUhRZjhoR0Q2cVBtOXZyY1VB
            cjFXdjJkOE5RVlAxd091UmtQeEUxVE0Kwgi0dSti3LrO29Llpzq/waKxR6hU4G4o
            W0WVw36WDQvxWMO3saLp1Wi6k2SS59OXh5TV0Oz7h/67mqcXS6//dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uugu7jllxc3lpfzn96wm0kylr0v5m5a0adtg25yst5nn5e3muyssrcyys3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T15:23:02Z"
    mac: ENC[AES256_GCM,data:DtmW71lcmJvExEud2w6SLcOqrjtOzs91FtLKsSBhoOI2iAhLsjhtEMm4l6RVOIjGV5d7+GiAbHQCX/+nFjRfBk2W9Kf9EftZ8aL5rbInBH0Mqx3CLghy8eUK57/P5GpdxxbNyvmUU9/cbJuPnqsyDjJLhAGdU+9VsA8Ahfxx7YE=,iv:xOkYTr0PGI7pQKP8Op8FqrM+iGBVQbrZR/bziHhLHAQ=,tag:PrppkrwcCRhES018FIwVlQ==,type:str]
    version: 3.13.3
