apiVersion: v1
kind: Secret
metadata:
    name: fishing-app-secret
    namespace: fishing
    labels:
        app.kubernetes.io/name: fishing-app
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fWK5wn7somr4JTV0DRQ24PjotJEhc3Gk2cwuxNcivw5XFEy7stqQRvt5pRiucz/JYdj9Ly8xzyUXnlX+UlDOCzdw,iv:WPdSbjCU/8xzEjxojXWUtNw/9ilWJ+caKgjmHOZIwrs=,tag:ReugxfDbZ7FqRX0hkB6jww==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:sRAyZcM2Cs/ExLDny0hcyA429kCja5foUVT1l3RHTxmPSfTqDjidqRVuy4zulflwh2+Emp4EBISLL9DKkFBIqck+6CliFww+wZ/qLmHmrJUHMOn3Rx7pSlkY+jOIbtHdEXXvVR7WvPrATyLnk1vWmuXrN392SjTfYljsVuINW08bHJkLgxeucDQV8r4jr8UiPzO6CrKVPc6IKglN,iv:fo7CD7CFX6OBjcUb5ok31PPRIqwBwZB160p195oL884=,tag:REeKixb+Bewce1aiUJogfQ==,type:str]
    #ENC[AES256_GCM,data:wJsowNmb8ITYmthhuWQFLz1oC4vSNok3QC6hxJo4RuY3rMz/L4UJAao4770yTM50M4iPE0Nz3h8=,iv:ny/1ce1fqK0Uflf7afYdBAOx3MWZjZQCX2Zx+PvTyUg=,tag:KX11826pxuXHhLzeOmvz9Q==,type:comment]
    DATABASE_URL_DIRECT: ENC[AES256_GCM,data:FrHDk7GuAkKwb5Dk8ogDNmYkyv+FQ13FFvcLqXdt1wKrCMgmGdlfnGi+tfjFIlMfLdL1vm/a9hJN69EQVoFr+B8xOFEkl5pepcyjQo/hIq6zRYl3aDmJ12Ymxf/0N+5p0VXyK/u8EwqZsikW3F38vzqLm0ypzP1g0sxkWthcYvtmcSL6Um/i6sL2UescP/12,iv:sWf+iT5C9ddAJIH7l7FP/ONvV9+N/VZJRQAA3Qp4Juw=,tag:qAXcdYFhGSK9xX6SQiYzEw==,type:str]
    #ENC[AES256_GCM,data:f3EgBanzcgXeuOAN5eYmUC1MU3nCTq+ZQ6+/IzkIG9/yIRldLcZcwiBSAA3pYuLxY7PUohZSJlz5mw==,iv:kpyXI3K90cWo+H9ku1bUdIL/oSNcuW9lHSfsxPivYSU=,tag:8SzzXmTr/PLslz5HzXWILQ==,type:comment]
    AUTH_SECRET: ENC[AES256_GCM,data:XZKtzFHVy4gQLbHtkDOv4czUReF5SUVZOFhhULH3/50C3uboYNQoMdvTstc=,iv:yMkYRjihry8Rw4MBPk6EDXJR/6tsDdE/eaQT68boL4w=,tag:leYPlHWfYN5Ec5RSpFL2+A==,type:str]
    AUTH_GOOGLE_ID: ENC[AES256_GCM,data:Nree68NmjUVsfjSbhvWPvsdBa41SiWO1XPp6Ppqgze4LzX3Pvq++cgILKm0TeEzyddyj3q+KbaFSz8qtHysqfYt1kaIdSfBe,iv:6PIszBiGWmU4m1jLoudS5Z17h1cT0X0L80IoYLfM7c4=,tag:+SsBbjnyQdxkYuLYDG+prA==,type:str]
    AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:uuQVMuhPxUDdFOofElgKqDKMJxnd094lapQeCrIGArHXJa0=,iv:eEcHG0ZdqbZ71ZWM4RewsjYKOsv0YAjw8v+g+SjlzkA=,tag:00HZhFyKvD5fRKSoZi04cA==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:ZCPAgrJ0ZWs/lkHOs4SYvNXZX3ojXLHefivSeGz+t2c=,iv:xgbOFKMJBKWl9dGAEhnxc7l99czTx+WqY3Cf8Vi4h2k=,tag:7P7HCR3kuJpgD6F2bpfPmw==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:J3c2m1t4SxDJJJSUjN0LyVosYooQUTg/SeQ4g7WJkLDkYkUP,iv:1poxGuH4NoWVf/bgB1kmg4sAfTUDiHN5fqOVCXq1aj4=,tag:m4xfdAqpsgZIlyHIo2rkAw==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:S9eeuGYZEImHmc4G5xnMwE+ohyG0zw==,iv:7F+3d4Se5QxAwz8O9H6g/GaHUR+TH0dxH/NDi+hZw2A=,tag:mw4lmg85Kr7xA9scyfhhaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT25qc0ZOQ3hmd0hOdXNE
            R081R2V3VUNmSkhiMjBrWURjaWM3eEduakdjCmxPOE9uOC84YTBBMXNjaWRhSlFM
            eVdlTDVUTzNCSmJGK1l1aTBIL0o3MEEKLS0tIExOSkNZS0xveldzQWJ0Q0k5M1N2
            WkVFajlHYTJHRFE1ZWJKdjM1MzlzZDAKEGT5LGXUA+p4CNCqNPztazzvfZFRecSr
            u6du4c4zmhqTDQY5fCYmhbSRDyRX37bsB/emrsQpmzhSDg4z6DCrMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwpnls59pm7a542w3s4le2sgrcqpvtxtchxumdl4qhwph4xu25wqpqjxpn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL3FCcEJpN1JNSjFxNjBW
            VGdCLzhqM2cvNFBhc0wxbk1DaDR5akdUaFVFCmhuRFBpeXVjTWhCUElFeFF0bXli
            bklYdVk3cCsrUURiNURLeFVXcno3QXcKLS0tIE8rZHEwdnVXMVlNd0MxNjRpSlBB
            L0hYU0tFY28wNHR4anhmN1VSR0RmZWMKPdGj07BgWdo6oLy493lSBissGlIJzL75
            Vkn6bgGjt3379S7ve+R3iq9HO6jQN1UOE0snhfbgCshxyFJVuVt1zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19243y8pewm9rq8ldjffptyvkfex2ytem2wncdhzj4gl8q0awyqqq0l56wk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVFdrVTJDRkdFU2Z4SlF0
            NXhjcEJnUEtFWjdVR28xQVlBUEx5VktmSmw0ClRyd2hzcExkdnFMMjhvdktCa1BR
            djlMTVlreW5uam8xaityc0pkYmoyNFkKLS0tIDBSVUhRZjhoR0Q2cVBtOXZyY1VB
            cjFXdjJkOE5RVlAxd091UmtQeEUxVE0Kwgi0dSti3LrO29Llpzq/waKxR6hU4G4o
            W0WVw36WDQvxWMO3saLp1Wi6k2SS59OXh5TV0Oz7h/67mqcXS6//dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uugu7jllxc3lpfzn96wm0kylr0v5m5a0adtg25yst5nn5e3muyssrcyys3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T13:42:35Z"
    mac: ENC[AES256_GCM,data:SKo+AEiRIvbGHw04yU6bwqDWUZME3Qc1oa/QlXIMd9ujOu0r+HmJB3Yg2LYQWPHgTpsnUaxW/yzm9WeYNrPp6xOPU3leO88lLjqCwSj8pSx+pIYw7T6gCCYzoRViBrrr+wK3b6oRgf0WcSLYzrSiylJ8pAqNXP0XY4CGV9MtG6E=,iv:u2Z71GNWt9EL9BObnKyvjiCPBgEhcaeonGAfH6//ndE=,tag:muPkE9YCtraYgpJG5wSYBw==,type:str]
    version: 3.13.3
