apiVersion: v1
kind: Secret
metadata:
    name: fishing-app-secret
    namespace: fishing
    labels:
        app.kubernetes.io/name: fishing-app
type: Opaque
stringData:
    #ENC[AES256_GCM,data:UKr9lg7cTjmpdTW8CoCN6Hq0HnRSrGkMeiuueLoiKkvBFhahgNXt3VnazpjWP5EeJfl97Wq0j1VhaHQ2t9DOPwIW,iv:c5P1jXUv/+/ALA0UIC++L4/Otof4nMDddXbz7Z9H2MU=,tag:OaXfkTAv/qOKWGfEY9IhNA==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:QGVXlBoQBQ0Cmk2tC+El7mB2hhwueD4sL1C+KxS1jbWO7f0US3LeJZtXGaECEmHS2EUAQiz6JbZw2L88r0ZC9xcvxwCjLLibROOPThsIGzLP8U4QfhFKUkX5iQPtExwKUiBWBt+xxNEx7AgPutKuTQk8zNft7bNIkUEbMdeT5xAIUAJj+S9ITrsliUEobJi0p035cP/qpacoOYfi,iv:1lfXPcoKUAIo2wrBqesO5z/dhKviaFWn5T2/5wZqI2o=,tag:QEDO/VqwEe5PF00vklM3JQ==,type:str]
    #ENC[AES256_GCM,data:Wd9wVvK9YcMDeATrLpxJJlqfDw19K+T3AgZKLOD5KKku2rPOsMCEZWwUME8w8PwzD67DqnQ1Or8=,iv:jTdl+pZjwZpovOdyKUjYET9v5XIMlOn55cpgEzbI/2w=,tag:sYwEyf56RtjkCc1uqgPO8w==,type:comment]
    DATABASE_URL_DIRECT: ENC[AES256_GCM,data:9NLlVJvvnhK5WPNQrY/lrcdyoR/AVTeGh+WzhxkwsNrM9LdDB5PJ2MIc2MZT0JMraGkFHWJwCC9uHX4ujwE75yaRBTrrk1JTiqMPa6ZvF1aPFwASj2krFwjPG5K7kNUthP1XpC520bLwADQ1dcfk2YPSq7lWx5LxA8oKthGDyQ==,iv:RqBFZOR0Vsoh2NseJLRgAgRpC6RlA2qJ1SmVPFSn1BA=,tag:QSBPWD6mzh7xq3poPttvtA==,type:str]
    #ENC[AES256_GCM,data:ffrNx1UADLTAL00vNMISMFzAX57LioScj4PxLG5duLgEsEAevV0t/I5B7Z+IeyFhDLTlCR39dh/IcQ==,iv:DD7TMfh0qEKUI7OkFhOv/499JrtOBa4D0p2enPpRy1s=,tag:gUzPXDypAXZeCFL2Vhnvhg==,type:comment]
    AUTH_SECRET: ENC[AES256_GCM,data:7DzlWtrn8BVrKjOwXwN9Li+JgX2dV3D1B89uVZ2LHWYd0IaiQRXvMXPk5vs=,iv:gKcxSai1rRkPiB8BlT8+gbSrPsRDI/R2tqYfgEJvzGo=,tag:PzKYcWOcymDul35K/hb7Vg==,type:str]
    AUTH_GOOGLE_ID: ENC[AES256_GCM,data:2PVB8NULNAUCId+3LJpfK8qNsVYvac6YAMlncGRovljsM3lwkyV5JITdo1wrzJyzflO+zu9cAOmgxCeSVtACkrz2MM6qb6ev,iv:TNXZMuF0bQmOx+oRYAV8MxDMfPObk00kGFmZHpDrt+k=,tag:kTfGHXVT4qmaGrZ1NisQZA==,type:str]
    AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:Dxa5Hs1SximlxoB3TP+W3j9LJVrNGW0DRZEDtomrzTs3M40=,iv:OyhJDGaannILzjRj7AoS5dOJQdFO/aqVdlzENyUF77M=,tag:DL3ooiEJmbFYJ1WmbXHcyg==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:YTqDLbkCw6CgOH1c/sxlEjEn981knrIycARkVp6zAI4=,iv:uY0g9t90jT4e1O9pvVHRWhw0ZjlHYuL25VK0WvWWGio=,tag:Wdkv/tO4dPTvIyRkgJ5+uA==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:ILGBBKCASAEP2qPaWVszI7XnzjkhCPzPRXjhm7218sN30luI,iv:GBQ4Vs2Km14uDgoFm7OZJK7q6YvAikXOiUTnqCaXQ9g=,tag:xWD34oeiUxOO+6KlVeh11g==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:Q7ONW3UyaW99XDa9sYN9E93WjyGD7Q==,iv:McC7nOE11I5i17Wx1h26XeW2XwiNP1cMgZFb7NjBrdU=,tag:eFXeFzwPDGPghdur3mcQBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZVp2dW80bGF0TTdJemJI
            cUg3Ui9JNE1FWUpPWFhHVk8rVVBWMmdhK3lJClhZUTBZN0xpNlVEdExtK0tlT1Aw
            OUdoaWpycnhBYkdvSWk4R3JRN0R6YlEKLS0tIDhONXNrMlcwNG5qdHZSb0VqZVZk
            RlVsRU9aMm5VNG4zKzEyZU9hZndPSmcKkS/+JVbo6uQDnigKjfXkhYh9JehVbkHT
            B+mHbO6BQ40OQNNMtfeceGSSeAqw/744a1vWVNtgrBA1BQUq2hcNgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwpnls59pm7a542w3s4le2sgrcqpvtxtchxumdl4qhwph4xu25wqpqjxpn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYmdwd0ppOEdXSW1UUStt
            ZTVPV1o1QmVscExJZWl1b0E4SjJkc25oekFvClloVjdQY05HNnpldDJNcHhXQzVX
            VTFaeVdYOGw1dm1Cczl5TkNEN2lCa1kKLS0tIHRhNU9PNTdOeVhDUzlOcnR4eWRG
            REwzNVhxNGViK3dvMmhabE5JNEdNRjgKJ7a7ByOHi/nin04/W49YJnK5puBKxtbl
            /VS+gRuOIVtg0Ay8amlLZN1v+W++Non1yAXnxKMiO9Chz4+BOOePXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19243y8pewm9rq8ldjffptyvkfex2ytem2wncdhzj4gl8q0awyqqq0l56wk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaUR4T3pyWXV2LytqUzJi
            T0dxOVd6RzdRclZkM3oza2hwdjdSenJKWnpRCjJPQXNCc2RobmovUXVqK2hUekp2
            bjRMOTgwU2NCQkxudjBHYk9KKzNCUDAKLS0tIE1aTEF5NlliR3oyNStNK3VuQW93
            bkRiOWdqMnowZ2xQdzRjOHJYS2Rydk0KeduzT/3l3nvM3KqcZpjclZGPkqxuAcVf
            ppUPiZ9JiRjaG5g2i6qw2rEiFn3XqwxDdqK/ztMnHv5bwQpDDe9CBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uugu7jllxc3lpfzn96wm0kylr0v5m5a0adtg25yst5nn5e3muyssrcyys3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T15:28:42Z"
    mac: ENC[AES256_GCM,data:yyc47XlNFs+4MAylZPTi9PzEOmIDOemI+gO2WURfMahyOu68XGq4RPv3paL0KWPvsLOcopcjccCaym8M8XYbqy4gJhqXuMJOWQ3nCDT7NVsEwiuojpv9No0B/cM+AY3R5DV5jHCbRW7BER+MaGPnXQGOHIU3FXWTVhhjZNvQjxM=,iv:iFR4FEKMjqLHTd0453kG95a1VgpM3xGKJDdKzCZSauE=,tag:yt4L0ZCHXPZBEJIHQp+pgw==,type:str]
    version: 3.13.3
