apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fishing-app
  namespace: fishing-app
  labels:
    app.kubernetes.io/name: fishing-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: fishing-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fishing-app
                port:
                  name: http
