apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fishing-app

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: fishing-app-config
    literals:
      - NODE_ENV=production
      - AUTH_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
